// Mock data for portfolio examples
export const mockPortfolios = [
  {
    id: 1,
    author: "Victor Eke",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://victoreke.com/",
    githubUrl: "https://github.com/example/portfolio1",
    techStack: ["React", "TailwindCSS", "Framer Motion", "Next.js"],
    description: "A minimalist portfolio with smooth animations and a focus on typography and whitespace.",
  },
  {
    id: 2,
    author: "Alex Chen",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio2",
    githubUrl: "https://github.com/example/portfolio2",
    techStack: ["Vue", "SCSS", "GSAP", "Three.js"],
    description: "Creative 3D portfolio with interactive elements and immersive experiences.",
  },
  {
    id: 3,
    author: "Maya Patel",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio3",
    githubUrl: "https://github.com/example/portfolio3",
    techStack: ["React", "Styled Components", "TypeScript", "Gatsby"],
    description: "Clean, accessible portfolio with a focus on performance and user experience.",
  },
  {
    id: 4,
    author: "James Wilson",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio4",
    githubUrl: "https://github.com/example/portfolio4",
    techStack: ["Angular", "Bootstrap", "RxJS", "TypeScript"],
    description: "Enterprise-focused portfolio showcasing complex data visualization projects.",
  },
  {
    id: 5,
    author: "Sophia Rodriguez",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio5",
    githubUrl: "https://github.com/example/portfolio5",
    techStack: ["Svelte", "TailwindCSS", "TypeScript", "Netlify"],
    description: "Fast, lightweight portfolio with creative micro-interactions and animations.",
  },
  {
    id: 6,
    author: "Ethan Kim",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio6",
    githubUrl: "https://github.com/example/portfolio6",
    techStack: ["Next.js", "Chakra UI", "Framer Motion", "TypeScript"],
    description: "Accessible portfolio with dark mode support and smooth page transitions.",
  },
  {
    id: 7,
    author: "Olivia Martinez",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio7",
    githubUrl: "https://github.com/example/portfolio7",
    techStack: ["React", "Material UI", "Redux", "Firebase"],
    description: "Interactive portfolio with real-time features and a playful design approach.",
  },
  {
    id: 8,
    author: "Daniel Lee",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio8",
    githubUrl: "https://github.com/example/portfolio8",
    techStack: ["Vue", "Vuetify", "TypeScript", "GraphQL"],
    description: "Data-driven portfolio showcasing complex visualization projects and API integrations.",
  },
  {
    id: 9,
    author: "Emma Thompson",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio9",
    githubUrl: "https://github.com/example/portfolio9",
    techStack: ["React", "TailwindCSS", "Three.js", "Sanity.io"],
    description: "Creative portfolio with 3D elements and a content management system for easy updates.",
  },
  {
    id: 10,
    author: "Noah Garcia",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio10",
    githubUrl: "https://github.com/example/portfolio10",
    techStack: ["Svelte", "SCSS", "TypeScript", "Vercel"],
    description: "Performance-focused portfolio with a unique scrolling experience and custom animations.",
  },
  {
    id: 11,
    author: "Ava Williams",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio11",
    githubUrl: "https://github.com/example/portfolio11",
    techStack: ["Next.js", "TailwindCSS", "Framer Motion", "Prisma"],
    description: "Full-stack portfolio with a blog, project showcase, and contact form integration.",
  },
  {
    id: 12,
    author: "Liam Brown",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio12",
    githubUrl: "https://github.com/example/portfolio12",
    techStack: ["React", "Emotion", "TypeScript", "Contentful"],
    description: "Content-rich portfolio with a focus on storytelling and project case studies.",
  },
  {
    id: 13,
    author: "Isabella Clark",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio13",
    githubUrl: "https://github.com/example/portfolio13",
    techStack: ["Angular", "SCSS", "NgRx", "Firebase"],
    description: "State-managed portfolio with complex interactions and real-time data updates.",
  },
  {
    id: 14,
    author: "Mason Taylor",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio14",
    githubUrl: "https://github.com/example/portfolio14",
    techStack: ["Vue", "TailwindCSS", "Pinia", "Supabase"],
    description: "Modern portfolio with authentication features and a project management dashboard.",
  },
  {
    id: 15,
    author: "Charlotte Adams",
    screenshot: "/placeholder.svg?height=400&width=600",
    liveUrl: "https://example.com/portfolio15",
    githubUrl: "https://github.com/example/portfolio15",
    techStack: ["React", "Chakra UI", "React Query", "Strapi"],
    description: "API-focused portfolio with efficient data fetching and a headless CMS integration.",
  },
]
