
// Mock data for portfolio examples
export const mockPortfolios = [
  {
    id: 1,
    author: "Victor Eke",
    screenshot: "/id1.jpg",
    liveUrl: "https://victoreke.com/",
    githubUrl: "https://github.com/evavic44/victoreke.com",
    techStack: ["Nextjs", "Sanity", "Tailwind CSS", "TypeScript", "Umami", "Vercel"],
    description: "Modern Next.js portfolio with Sanity CMS integration and TypeScript for type safety.",
  },
  {
    id: 2,
    author: "Kent C. Dodds",
    screenshot: "/id2.png",
    liveUrl: "https://kentcdodds.com/",
    githubUrl: "https://github.com/kentcdodds/kentcdodds.com",
    techStack: ["React", "TypeScript", "Remix", "Prisma", "Redis", "Postgres", "CSS"],
    description: "Full-stack React portfolio with Remix, database integration, and modern web technologies.",
  },
  {
    id: 3,
    author: "Brittany Chiang",
    screenshot: "/id3.png",
    liveUrl: "https://v4.brittanychiang.com/",
    githubUrl: "https://github.com/bchiang7/v4",
    techStack: ["React", "Gatsby", "Styled-components"],
    description: "Elegant React portfolio built with Gatsby and styled-components for a polished look.",
  },
  {
    id: 4,
    author: "Braydon Coyer",
    screenshot: "/id4.png",
    liveUrl: "https://braydoncoyer.dev/",
    githubUrl: "https://github.com/braydoncoyer/braydoncoyer.dev",
    techStack: ["React", "TypeScript", "NextJS", "Tailwindcss", "Notion API", "Supabase"],
    description: "Dynamic portfolio with Notion API integration and Supabase backend for content management.",
  },
  {
    id: 5,
    author: "Tania Rascia",
    screenshot: "/id5.png",
    liveUrl: "https://taniarascia.com/",
    githubUrl: "https://github.com/taniarascia/taniarascia.com",
    techStack: ["React", "Gatsby", "CSS", "Netlify", "NodeJS"],
    description: "Content-focused portfolio with Gatsby, featuring a blog and tutorial sections.",
  },
  {
    id: 6,
    author: "Jemima Abu",
    screenshot: "/id6.png",
    liveUrl: "https://jemimaabu.com/",
    githubUrl: "https://github.com/jemimaabu/portfolio",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Clean vanilla JavaScript portfolio with modern CSS animations and responsive design.",
  },
  {
    id: 7,
    author: "Rekhchand Sahu",
    screenshot: "/id7.png",
    liveUrl: "https://rekhchandsahu.com/",
    githubUrl: "None",
    techStack: ["React"," Gatsby", "Preact", "GSAP"],
    description: "Performance-optimized portfolio with GSAP animations and Preact for faster rendering.",
  },
  {
    id: 8,
    author: "Olaolu Olawuyi",
    screenshot: "/id8.png",
    liveUrl: "https://olaolu.dev/",
    githubUrl: "https://github.com/whizkydee/olaolu.dev",
    techStack: ["VueJS", "JavaScript", "HTML", "styled-components", "Sass"],
    description: "Vue.js portfolio with styled-components and Sass for advanced styling capabilities.",
  },
  {
    id: 9,
    author: "Thang Huu Vu",
    screenshot: "/id9.png",
    liveUrl: "https://www.thvu.dev/",
    githubUrl: "https://github.com/ThangHuuVu/thvu-blog",
    techStack: [	"React", "NextJS"," NodeJS", "TypeScript", "GraphQL", "Tailwindcss"],
    description: "Full-stack portfolio with GraphQL API, TypeScript, and modern development practices.",
  },
  {
    id: 10,
    author: "George Francis",
    screenshot: "/id10.png",
    liveUrl: "https://georgefrancis.dev/",
    githubUrl: "None",
    techStack: ["GSAP", "Netlify", "HTML", "CSS", "JavaScript"],
    description: "Animation-heavy portfolio showcasing GSAP for smooth, professional web animations.",
  },
  {
    id: 11,
    author: "Aditya Vikram",
    screenshot: "/id11.png",
    liveUrl: "https://people.umass.edu/avsingh",
    githubUrl: "https://github.com/AVS1508/My-Alternate-Portfolio-Website",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Simple yet effective portfolio built with vanilla web technologies and clean design.",
  },
  {
    id: 12,
    author: "Adeola Adeoti",
    screenshot: "/id12.png",
    liveUrl: "https://www.adeolaadeoti.site/",
    githubUrl: "https://github.com/adeolaadeoti/adeolaadeoti-v2",
    techStack: ["TypeScript", "GSAP", "NodeJS", "NextJS", "SCSS"],
    description: "TypeScript-powered portfolio with GSAP animations and SCSS for advanced styling.",
  },
  {
    id: 13,
    author: "Dejan Markovic",
    screenshot: "/id13.png",
    liveUrl: "https://www.dejan.works/",
    githubUrl: "None",
    techStack: ["HTML", "CSS", "JavaScript", "Jquery"],
    description: "Classic portfolio using jQuery for interactive elements and smooth user experience.",
  },
  {
    id: 14,
    author: "Max Böck",
    screenshot: "/id14.png",
    liveUrl: "https://mxb.dev/",
    githubUrl: "https://github.com/maxboeck/mxb",
    techStack: ["Eleventy", "SCSS", "Nunjucks"],
    description: "Static site portfolio built with Eleventy, featuring fast performance and clean code.",
  },
  {
    id: 15,
    author: "David Darnes",
    screenshot: "/id15.png",
    liveUrl: "https://darn.es/",
    githubUrl: "none",
    techStack: ["Netlify", "Jekyll", "ETC"],
    description: "Jekyll-based portfolio with Netlify deployment for reliable hosting and fast loading.",
  },
  {
    id: 16,
    author: "Schulz Daniel",
    screenshot: "/id16.png",
    liveUrl: "https://iamschulz.com/",
    githubUrl: "https://github.com/iamschulz/iamschulz-hugo",
    techStack: ["Hugo", "Shell", "JavaScript"],
    description: "Hugo static site portfolio with custom shell scripts for efficient development workflow.",
  },
  {
    id: 17,
    author: "Rafael Conde",
    screenshot: "/id17.png",
    liveUrl: "https://rafa.design/",
    githubUrl: "https://github.com/rafaelconde/rafaelconde",
    techStack: ["Nunjucks", "JavaScript", "CSS"],
    description: "Design-focused portfolio using Nunjucks templating for clean, maintainable code structure.",
  },
  {
    id: 18,
    author: "Bruno Simon",
    screenshot: "/id18.png",
    liveUrl: "https://bruno-simon.com/",
    githubUrl: "https://github.com/brunosimon/folio-2019",
    techStack: ["GSAP", "ThreeJS", "JavaScript", "ETC"],
    description: "Immersive 3D portfolio showcasing Three.js and GSAP for cutting-edge web experiences.",
  },
  {
    id: 19,
    author: "Oluwadare Oluwaseyi",
    screenshot: "/id19.png",
    liveUrl: "https://www.seyi.dev/",
    githubUrl: "https://github.com/oluwadareseyi/folio-v2",
    techStack: ["HTML", "SCSS", "JavaScript", "GSAP"],
    description: "Modern portfolio with SCSS architecture and GSAP animations for engaging user interactions.",
  },
  {
    id: 20,
    author: "Jason Lengstorf",
    screenshot: "/id20.png",
    liveUrl: "https://www.jason.energy/",
    githubUrl: "https://github.com/jlengstorf/jason.energy",
    techStack: ["JavaScript", "TypeScript", "Nunjucks", "CSS"],
    description: "Energy-themed portfolio built with TypeScript and Nunjucks for robust, scalable development.",
  },
  {
    id: 101,
    author: "Stef Ivanov",
    screenshot: "/id101.png",
    liveUrl: "https://stefivanov.com/",
    githubUrl: "None",
    techStack: ["WordPress", "Yoast SEO", "MailChimp", "PWA", "Google Analytics", "Sumo"],
    description: "WordPress portfolio with Yoast SEO, MailChimp, PWA, Google Analytics, and Sumo for enhanced user experience.",
  },
  {
    id: 102,
    author: "Erika Senft Miller",
    screenshot: "/id102.png",
    liveUrl: "https://www.erikasenftmiller.com/",
    githubUrl: "None",
    techStack: ["Contentful", "GSAP", "LazySizes", "PWA", "Google Analytics"],
    description: "Contentful-powered portfolio with GSAP animations, LazySizes for image optimization, and PWA for enhanced user experience.",
  },
  {
    id: 103,
    author: "Ruben Kuipers",
    screenshot: "/103.png",
    liveUrl: "https://rubenkuipers.design/",
    githubUrl: "None",
    techStack: ["Vue.js", "Nuxt.js", "Tailwind CSS", "scrollreveal", "Google Tag Manager", "Google Analytics"],
    description: "Vue.js portfolio with Nuxt.js, Tailwind CSS, scrollreveal, Google Tag Manager, and Google Analytics for enhanced user experience.",
  },
  {
    id: 104,
    author: "Maggie Appleton",
    screenshot: "/104.png",
    liveUrl: "https://maggieappleton.com/",
    githubUrl: "https://github.com/MaggieAppleton/maggieappleton.com-V2",
    techStack: ["React", "Next.js", "MDX", "Algolia Search", "Reach UI", "Tippy.js", "Framer Motion", "styled-components", "Lodash"],
    description: "Content-rich portfolio with MDX, Algolia search, and advanced React components for enhanced user experience.",
  },
  {
    id: 105,
    author: "Moe Dayraki",
    screenshot: "/id105.jpg",
    liveUrl: "https://moe.dayrakiarts.com/",
    githubUrl: "https://github.com/moedayraki/moedayraki.github.io",
    techStack: ["Vue 3", "Vite", "Cypress", "Tailwindcss", "Typescript", "Pinia", "Primevue", "magic.css", "VueUse"],
    description: "Modern Vue 3 portfolio with Vite, TypeScript, and comprehensive testing using Cypress.",
  },
  {
    id: 106,
    author: "Truong Phan",
    screenshot: "/id106.png",
    liveUrl: "https://techika.com/",
    githubUrl: "https://github.com/infantiablue",
    techStack: ["Vue 3", "Vite", "VuePress", "Tailwindcss", "Tailwind", "Lighthouse"],
    description: "Vue 3 portfolio with VuePress documentation and Lighthouse optimization for performance.",
  },
  {
    id: 107,
    author: "Wasim Baig",
    screenshot: "/id107.png",
    liveUrl: "https://wasimbaig.com/",
    githubUrl: "https://github.com/simbaig/portfolio-nextjs",
    techStack: ["Next JS", "Tailwind CSS", "Framer-Motion"],
    description: "Next.js portfolio with Tailwind CSS and Framer Motion for smooth animations and modern design.",
  },
  {
    id: 108,
    author: "Mike Bifulco",
    screenshot: "/id108.png",
    liveUrl: "https://mikebifulco.com/",
    githubUrl: "https://github.com/mbifulco/blog",
    techStack: ["NextJS", "React", "SCSS", "MDX", "Vercel"],
    description: "Next.js blog portfolio with MDX content management and SCSS for advanced styling.",
  },
  {
    id: 109,
    author: "Shodipo Ayomide",
    screenshot: "/id109.png",
    liveUrl: "https://shodipoayomide.com/",
    githubUrl: "https://github.com/Developerayo/shodipoayomide.com",
    techStack: ["Gatsby", "React", "SCSS", "Bootstrap", "Jquery"],
    description: "Gatsby portfolio with Bootstrap and jQuery for enhanced interactivity and responsive design.",
  },
  {
    id: 110,
    author: "Damian Watracz",
    screenshot: "/id110.png",
    liveUrl: "https://watracz.com/",
    githubUrl: "None",
    techStack: [	"HTML", "CSS", "JavaScript", "Swiper"],
    description: "Vanilla JavaScript portfolio with Swiper for smooth carousel and slider functionality.",
  },
  {
    id: 111,
    author: "Franklin Ohaegbulam",
    screenshot: "/id111.png",
    liveUrl: "https://frankiefab.com/",
    githubUrl: "https://github.com/frankiefab100/frankiefab.tech",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Clean vanilla web portfolio with modern JavaScript and responsive CSS design.",
  },
  {
    id: 112,
    author: "Samuel Akinosho",
    screenshot: "/id112.png",
    liveUrl: "https://www.samuelakinosho.com/",
    githubUrl: "None",
    techStack: ["Webflow", "Jquery"],
    description: "Webflow-based portfolio with jQuery for enhanced user interactions and dynamic content.",
  },
  {
    id: 113,
    author: "Rutik Wankhade",
    screenshot: "/id113.png",
    liveUrl: "https://rutikwankhade.dev/",
    githubUrl: "None",
    techStack: [	"NextJs", "React", "NodeJS", "TailwindCSS"],
    description: "Full-stack Next.js portfolio with Node.js backend and Tailwind CSS for modern styling.",
  },
  {
    id: 114,
    author: "Adenekan Wonderful",
    screenshot: "/id114.png",
    liveUrl: "https://www.codewonders.dev/",
    githubUrl: "None",
    techStack: ["React", "NextJS", "Styled-components"],
    description: "React portfolio with Next.js and styled-components for component-based styling architecture.",
  },
  {
    id: 115,
    author: "Olamide Sholanke",
    screenshot: "/id115.png",
    liveUrl: "https://www.olamide.dev/",
    githubUrl: "None",
    techStack: [	"Vue"," NuxtJS"],
    description: "Vue.js portfolio with Nuxt.js for server-side rendering and enhanced performance.",
  },
  {
    id: 116,
    author: "Daniel Ezekiel",
    screenshot: "/id116.png",
    liveUrl: "https://danielezekiel.me/",
    githubUrl: "https://github.com/Daniel-Ezekiel/Portfolio-Website",
    techStack: [	"HTML", "CSS", "JavaScript"],
    description: "Simple and effective portfolio built with vanilla web technologies and clean design principles.",
  },
  {
    id: 117,
    author: "Julia Johnson",
    screenshot: "/id117.png",
    liveUrl: "https://www.juliacodes.com/",
    githubUrl: "https://github.com/juliacodes/JuliaCodesGatsby",
    techStack: ["React", "Styled-components"],
    description: "React portfolio with styled-components for modern, maintainable CSS-in-JS styling.",
  },
  {
    id: 118,
    author: "Rida F'kih",
    screenshot: "/id118.png",
    liveUrl: "https://www.rida.dev/",
    githubUrl: "https://github.com/ridafkih/portfolio",
    techStack: ["React", "NextJS"],
    description: "React portfolio with Next.js for optimal performance and developer experience.",
  },
  {
    id: 119,
    author: "Anand Baraik",
    screenshot: "/id119.png",
    liveUrl: "https://anandbaraik-folio.netlify.app/",
    githubUrl: "https://github.com/anandbaraik/anandfolio",
    techStack: ["HTML", "CSS"],
    description: "Minimalist portfolio built with pure HTML and CSS for fast loading and simplicity.",
  },
  {
    id: 120,
    author: "Abhishek Jha",
    screenshot: "/id120.png",
    liveUrl: "https://www.abhishekjha.me/",
    githubUrl: "None",
    techStack: ["HTML", "CSS", "JavaScript", "Ruby on Rails", "GSAP"],
    description: "Full-stack portfolio with Ruby on Rails backend and GSAP for advanced animations.",
  },
  {
    id: 121,
    author: "Olamide Adeyi",
    screenshot: "/id121.png",
    liveUrl: "https://www.olamideadeyi.com/",
    githubUrl: "None",
    techStack: ["Vue", "NuxtJS", "GSAP"],
    description: "Vue.js portfolio with Nuxt.js for SSR and GSAP animations for smooth interactions.",
  },
  {
    id: 122,
    author: "Greg Ives",
    screenshot: "/id122.png",
    liveUrl: "https://www.gregives.co.uk/",
    githubUrl: "https://github.com/gregives/gregives.co.uk",
    techStack: ["Vue", "NuxtJS", "SASS", "Netlify"],
    description: "Vue.js portfolio with Nuxt.js, SASS styling, and Netlify deployment for fast performance.",
  },
  {
    id: 123,
    author: "Collins Enebeli",
    screenshot: "/id123.png",
    liveUrl: "https://kadet.dev/",
    githubUrl: "https://github.com/kadetXx/kadet.dev",
    techStack: [	"React", "Gatsby"],
    description: "React portfolio built with Gatsby for static site generation and optimal performance.",
  },
  {
    id: 124,
    author: "Cole_Solomon",
    screenshot: "/id124.png",
    liveUrl: "https://colesolomon.me/",
    githubUrl: "https://github.com/codecole/colesolomonme",
    techStack: [	"HTML", "CSS", "SASS", "JavaScript", "GSAP", "W3js", "PHP"],
    description: "Full-stack portfolio with vanilla web technologies, GSAP animations, and PHP backend.",
  },
  {
    id: 125,
    author: "Adewale Adeyemi",
    screenshot: "/id125.png",
    liveUrl: "https://adex.onrender.com/",
    githubUrl: "https://github.com/dev-adewale/portfolio",
    techStack: [	"Gridsome", "GraphQL", "Tailwind"],
    description: "Gridsome portfolio with GraphQL data layer and Tailwind CSS for modern styling.",
  },
  {
    id: 126,
    author: "Harsh Singh",
    screenshot: "/id126.png",
    liveUrl: "https://harshsingh.xyz/",
    githubUrl: "https://github.com/harshhhdev/harshhhdev.github.io",
    techStack: [	"NextJS", "TailwindCSS", "TypeScript", "Prisma"],
    description: "Next.js portfolio with TypeScript, Tailwind CSS, and Prisma for database management.",
  },
  {
    id: 127,
    author: "Wallace Nascimento",
    screenshot: "/id127.png",
    liveUrl: "https://portfolio-srnascimento40.vercel.app/",
    githubUrl: "https://github.com/SrNascimento40/portfolio",
    techStack: [	"NextJS", "ReactJS", "TypeScript", "Styled-Components"],
    description: "Next.js portfolio with TypeScript and styled-components for component-based styling.",
  },
  {
    id: 128,
    author: "Idris Olubisi",
    screenshot: "/id128.png",
    liveUrl: "https://idrisolubisi.com/",
    githubUrl: "https://github.com/Olanetsoft/idrisolubisi.com",
    techStack: [	"ReactJs", "GatsbyJs", "TypedJs", "Styled Component"],
    description: "React portfolio with Gatsby, TypeScript, and styled-components for modern development.",
  },
  {
    id: 129,
    author: "Aycan Öğüt",
    screenshot: "/id129.png",
    liveUrl: "https://www.aycan.dev/",
    githubUrl: "https://github.com/aycanogut/aycan.dev",
    techStack: [	"React", "Next", "TypeScript", "Mantine"],
    description: "React portfolio with Next.js, TypeScript, and Mantine UI components for rapid development.",
  },
  {
    id: 130,
    author: "Manish Kumar",
    screenshot: "/id130.png",
    liveUrl: "https://manishk.dev/",
    githubUrl: "https://github.com/manishprivet/portfolio",
    techStack: [	"React", "Next", "TypeScript", "ParticleJS", "Firebase", "Vercel"],
    description: "Full-stack React portfolio with ParticleJS effects, Firebase backend, and Vercel deployment.",
  },
  {
    id: 131,
    author: "Andrea Toffanello",
    screenshot: "/id131.png",
    liveUrl: "https://andreatoffanello.com/",
    githubUrl: "None",
    techStack: [	"VueJS", "ThreeJS", "GSAP", "Blender"],
    description: "Immersive Vue.js portfolio with Three.js 3D graphics, GSAP animations, and Blender assets.",
  },
  {
    id: 132,
    author: "Chandraprakash Darji",
    screenshot: "/id132.png",
    liveUrl: "https://chandraprakash.vercel.app/",
    githubUrl: "https://github.com/Chandraprakash-Darji/personal",
    techStack: [	"Nextjs", "Typescript", "Tailwindcss", "Vercel"],
    description: "Next.js portfolio with TypeScript, Tailwind CSS, and Vercel for optimal performance.",
  },
  {
    id: 133,
    author: "Khaled Mohamed",
    screenshot: "/id133.png",
    liveUrl: "https://portfolio-john2.netlify.app/",
    githubUrl: "None",
    techStack: [	"HTML5", "SCSS", "Bootstrap5", "JavaScript", "SwipperJS", "Netlify"],
    description: "Modern portfolio with Bootstrap 5, SCSS, SwiperJS carousels, and Netlify deployment.",
  },
  {
    id: 134,
    author: "Michael Kolesidis",
    screenshot: "/id134.png",
    liveUrl: "https://michaelkolesidis.com/",
    githubUrl: "https://github.com/michaelkolesidis/michaelkolesidis.com",
    techStack: [	"TypeScript"," p5.js", "Sass", "Vite"],
    description: "Creative portfolio with TypeScript, p5.js for interactive graphics, and Vite build tool.",
  },
  {
    id: 135,
    author: "Piyush Goyani",
    screenshot: "/id135.png",
    liveUrl: "https://piyushgoyani.thesourcepedia.org/",
    githubUrl: "None",
    techStack: [	"VueJS", "Gridsome", "TailwindCSS", "Firebase"],
    description: "Vue.js portfolio with Gridsome static site generator, Tailwind CSS, and Firebase integration.",
  },
  {
    id: 136,
    author: "Vanessa Santana",
    screenshot: "/id136.png",
    liveUrl: "https://www.nessajs.com.br/",
    githubUrl: "https://github.com/vanessa-dev/nessa.js",
    techStack: [	"HTML", "CSS", "JavaScript", "PHP"],
    description: "Full-stack portfolio with vanilla web technologies and PHP backend for dynamic content.",
  },
  {
    id: 137,
    author: "Mahmoud Elkariouny",
    screenshot: "/id137.jpg",
    liveUrl: "https://clear-sleet.surge.sh/",
    githubUrl: "https://github.com/mahmoudessam820/my_portfolio",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Clean vanilla web portfolio with modern JavaScript and responsive CSS design.",
  },
  {
    id: 138,
    author: "Antonio Ayola",
    screenshot: "/id138.jpg",
    liveUrl: "https://github.com/vchaitanyachowdari/portfolio-ideas-1/blob/main/antonioayola.netlify.app",
    githubUrl: "https://github.com/Tono2007/Portafolio",
    techStack: [	"React", "HTML", "CSS", "Modules CSS", "JavaScript", "PWA"],
    description: "React PWA portfolio with CSS modules and progressive web app features for mobile experience.",
  },
  {
    id: 139,
    author: "Ajo Alex",
    screenshot: "/id139.png",
    liveUrl: "https://devpenzil.dev/",
    githubUrl: "https://github.com/devpenzil/devpenzil.dev",
    techStack: [	"NextJS", "Tailwind", "GraphCMS"],
    description: "Next.js portfolio with Tailwind CSS and GraphCMS headless CMS for content management.",
  },
  {
    id: 140,
    author: "Erys Mozo",
    screenshot: "/id140.jpg",
    liveUrl: "https://erysmozo.vercel.app/",
    githubUrl: "https://github.com/ErysCode7/Web-Portfolio",
    techStack: ["React", "SASS", "Vite", "AOS"],
    description: "React portfolio with SASS styling, Vite build tool, and AOS scroll animations.",
  },
  {
    id: 141,
    author: "Peace Jinadu-Paul",
    screenshot: "/id141.png",
    liveUrl: "https://pjpportfolio.netlify.app/",
    githubUrl: "https://github.com/Pappyjay23/my-portfolio-1",
    techStack: [	"React"," HTML", "CSS", "Javascript", "Framer Motion"," Netlify"],
    description: "React portfolio with Framer Motion animations and Netlify deployment for smooth interactions.",
  },
  {
    id: 142,
    author: "Hari Prasad",
    screenshot: "/id142.png",
    liveUrl: "https://hariprasd.me/",
    githubUrl: "https://github.com/hariprasd",
    techStack: ["React", "Tailwind CSS"],
    description: "Clean React portfolio with Tailwind CSS for modern, utility-first styling approach.",
  },
  {
    id: 143,
    author: "Danilo Batson",
    screenshot: "/id143.png",
    liveUrl: "https://batson-portfolio.vercel.app/",
    githubUrl: "https://github.com/danilobatson/batson-portfolio",
    techStack: [	"TypeScript", "JavaScript", "Python", "React", "React Native", "Vue", "Express", " Node", "MongoDB", "Next JS"],
    description: "Full-stack developer portfolio showcasing expertise across multiple technologies and frameworks.",
  },
  {
    id: 144,
    author: "Soumyadeep Das Bhowmick",
    screenshot: "/id144.png",
    liveUrl: "https://soumyadeeposd.github.io/Tensor-Block/",
    githubUrl: "https://github.com/SoumyadeepOSD/Tensor-Block",
    techStack: [	"HTML", "CSS", "JavaScript"],
    description: "Simple and effective portfolio built with vanilla web technologies and clean design.",
  },
  {
    id: 145,
    author: "Byunggeun Cho",
    screenshot: "/id145.png",
    liveUrl: "https://bbangjo.kr/",
    githubUrl: "https://github.com/bbangjooo/buffalo",
    techStack: ["HTML", "CSS", "JavaScript", "TypeScript", "Threejs", "Blender"],
    description: "Creative portfolio with Three.js 3D graphics, TypeScript, and Blender 3D assets.",
  },
  {
    id: 146,
    author: "James Warner",
    screenshot: "/id146.png",
    liveUrl: "https://jmswrnr.com/",
    githubUrl: "None",
    techStack: ["NextJS", "Sanity"," CSS", "Preact", "NodeJS", "ThreeJS"],
    description: "Next.js portfolio with Sanity CMS, Preact for performance, and Three.js 3D elements.",
  },
  {
    id: 147,
    author: "Maxime Heckel",
    screenshot: "/id147.png",
    liveUrl: "https://maximeheckel.com/",
    githubUrl: "https://github.com/MaximeHeckel/blog.maximeheckel.com",
    techStack: [	"NextJS", "TypeScript", "Stiches/CSS", "MDX"],
    description: "Next.js blog portfolio with TypeScript, Stitches CSS-in-JS, and MDX for content.",
  },
  {
    id: 148,
    author: "Twan Mulder",
    screenshot: "/id148.png",
    liveUrl: "https://www.twanmulder.com/",
    githubUrl: "https://github.com/twanmulder/portfolio",
    techStack: ["React", "TailwindCSS", "Stripe", "Netlify"],
    description: "React portfolio with Tailwind CSS, Stripe integration for payments, and Netlify deployment.",
  },
  {
    id: 149,
    author: "Rishi Mohan",
    screenshot: "/id149.png",
    liveUrl: "https://rishimohan.me/",
    githubUrl: "https://github.com/rishimohan/rishimohan.me",
    techStack: [	"Next.js", "TailwindCSS", "Framer Motion"],
    description: "Next.js portfolio with Tailwind CSS and Framer Motion for smooth, professional animations.",
  },
  {
    id: 150,
    author: "Nikhil Rajput",
    screenshot: "/id150.png",
    liveUrl: "https://nixrajput.nixlab.co.in/",
    githubUrl: "https://github.com/nixrajput/portfolio-nextjs",
    techStack: ["Next.js", "SCSS", "Node.js"],
    description: "Next.js portfolio with SCSS for advanced styling and Node.js backend capabilities.",
  },
  {
    id: 151,
    author: "Raphaël Chelly",
    screenshot: "/id151.png",
    liveUrl: "https://www.raphaelchelly.com/",
    githubUrl: "https://github.com/raphaelchelly/raph_www",
    techStack: [	"Next.js", "TailwindCSS", "Vercel"],
    description: ". A minimal and performant Next.js portfolio with TailwindCSS, hosted on Vercel.",
  },
  {
    id: 152,
    author: "Damian Demasi",
    screenshot: "/id152.png",
    liveUrl: "https://www.damiandemasi.com/",
    githubUrl: "https://github.com/Colo-Codes/portfolio-v2",
    techStack: [	"ReactJS", "TailwindCSS", "DaisyUI"],
    description: "A sleek React portfolio with TailwindCSS and DaisyUI, emphasizing modern UI.",
  },
  {
    id: 153,
    author: "Ifedili Onyegbu",
    screenshot: "/id153.png",
    liveUrl: "https://www.ifedili.com/",
    githubUrl: "https://github.com/saucecodee/ifedili.com",
    techStack: ["Angular", "TypeScript", "SASS"],
    description: " A clean Angular-based portfolio built with TypeScript and SASS.",
  },
  {
    id: 154,
    author: "Daniel Cranney",
    screenshot: "/id154.png",
    liveUrl: "https://www.danielcranney.com/",
    githubUrl: "https://github.com/danielcranney/portfolio",
    techStack: [	"NextJS", "TailwindCSS", "Vercel"],
    description: "A personal portfolio built with Next.js and TailwindCSS, deployed via Vercel.",
  },
  {
    id: 155,
    author: "Abdellatif Laghjaj",
    screenshot: "/id155.png",
    liveUrl: "https://www.abdellatif-laghjaj.ml/",
    githubUrl: "None",
    techStack: ["VueJS", "Lottilefiles", "Vercel", "CSS"],
    description: "A creative VueJS portfolio using CSS animations and Lottiefiles.",
  },
  {
    id: 156,
    author: "Adham Dannaway",
    screenshot: "/id156.png",
    liveUrl: "https://www.adhamdannaway.com/",
    githubUrl: "None",
    techStack: [	"Wordpress", "PHP", "jQuery", "MySQL"],
    description: "A dual-purpose designer/developer WordPress portfolio with jQuery elements.",
  },
  {
    id: 157,
    author: "Khaled Mohamed",
    screenshot: "/id157.jpeg",
    liveUrl: "https://james-oliver-portfolio.netlify.app/",
    githubUrl: "None",
    techStack: [	"HTML5", "CSS3", "SCSS", "Bootstrap5", "TypeScript", "SwipperJS", "Fontello", "PurgeCSS", "Netlify"],
    description: " A stylish static portfolio using HTML, SCSS, Bootstrap5, and TypeScript.",
  },
  {
    id: 158,
    author: "Glayson Visgueira",
    screenshot: "/id158.png",
    liveUrl: "https://glaysonvisgueira.vercel.app/",
    githubUrl: "https://github.com/Glaysonvisgueira/glaysonvisgueira_next-js",
    techStack: [	"NextJS", "Styled-components", "NodeJS", "Vercel", "Animate.css", "Lottiefiles"],
    description: "A vibrant Next.js portfolio with styled-components and animated effects",
  },
  {
    id: 159,
    author: "Chai Phonbopit",
    screenshot: "/id159.png",
    liveUrl: "https://devahoy.com/",
    githubUrl: "None",
    techStack: [	"NextJS", "Preact", "Tailwind CSS", "NodeJS"],
    description: "A tech blog-style portfolio built using Next.js, Preact, and TailwindCSS.",
  },
  {
    id: 160,
    author: "Aravind Balla",
    screenshot: "/id160.png",
    liveUrl: "https://aravindballa.com/",
    githubUrl: "https://github.com/aravindballa/website",
    techStack: ["NextJS", "TypeScript", "Tailwind CSS", "Vercel"],
    description: "A simple and fast developer portfolio using Next.js and TypeScript.",
  },
  {
    id: 161,
    author: "Khaled Mohamed",
    screenshot: "/id161.jpeg",
    liveUrl: "https://thomas-david-portfolio.netlify.app/",
    githubUrl: "None",
    techStack: ["React JS", "Tailwind CSS", "AOS", "SwipperJS", "React Scroll", "React Icons", "React Laze Load Image", "PostCSS", "Netlify"],
    description: "A responsive React portfolio with TailwindCSS and interactive UI libraries.",
  },
  {
    id: 162,
    author: "Tanishka Yadav",
    screenshot: "/id162.png",
    liveUrl: "https://tanishka-yadav.netlify.app/",
    githubUrl: "https://github.com/Tanishka-dev/Portfolio-Reactjs",
    techStack: [	"ReactJS", "Javascript", "SASS", "Framer Motion"],
    description: " A dynamic React portfolio enhanced with SASS and Framer Motion.",
  },
  {
    id: 163,
    author: "David Obodo",
    screenshot: "/id163.png",
    liveUrl: "https://www.davidobodo.com/",
    githubUrl: "None",
    techStack: [	"NextJS", "Typescript", "SASS", "GSAP", "Jest", "Sendgrid", "Google Analytics"],
    description: "A polished Next.js portfolio with GSAP animations and TypeScript.",
  },
  {
    id: 164,
    author: "Manuel David Gomez",
    screenshot: "/id164.png",
    liveUrl: "https://manueldavgomez.github.io/manueldavidgomez/",
    githubUrl: "https://github.com/ManuelDavGomez/manueldavidgomez",
    techStack: ["ReactJs", "Javascript", "Css", "Bootstrap", "Bootstrap Icons", "React-Animate-On-Scroll", "React-Scroll", "Vite", "TsParticles"],
    description: "A multi-featured React portfolio with scroll animations and Vite.",
  },
  {
    id: 165,
    author: "Olasunkanmi Balogun",
    screenshot: "/id165.png",
    liveUrl: "https://kanmibalogun.vercel.app/",
    githubUrl: "https://github.com/SiR-PENt/folio-me",
    techStack: ["NextJS", "JavaScript", "Tailwind", "Framer-motion", "vanilla CSS"],
    description: " A smooth Next.js portfolio using Tailwind, Framer Motion, and CSS.",
  },
  {
    id: 166,
    author: "Priyankar Pal",
    screenshot: "/id166.png",
    liveUrl: "https://itspp.vercel.app/",
    githubUrl: "https://github.com/priyankarpal/Priyankar",
    techStack: ["HTML & SCSS"],
    description: " A minimalist HTML and SCSS portfolio showcasing frontend skills.",
  },
  {
    id: 167,
    author: "Marieflor Bawanan",
    screenshot: "/id167.png",
    liveUrl: "https://marieflor.dev/",
    githubUrl: "https://github.com/mariebawanan/marieflor.dev",
    techStack: [	"NextJS", "TypeScript", "TailwindCSS", "GSAP"],
    description: "A TypeScript-based portfolio with Next.js, GSAP animations, and Tailwind.",
  },
  {
    id: 168,
    author: "Delba Oliviera",
    screenshot: "/id168.png",
    liveUrl: "https://delba.dev/",
    githubUrl: "https://github.com/delbaoliveira/website",
    techStack: ["Next.js", "MDX", "Tailwind", "Prisma", "Typescript"],
    description: "A personal blog-style portfolio using MDX, Prisma, and Tailwind.",
  },
  {
    id: 169,
    author: "Vivek Patel",
    screenshot: "/id169.png",
    liveUrl: "https://vivek9patel.github.io/",
    githubUrl: "https://github.com/vivek9patel/vivek9patel.github.io",
    techStack: [	"NextJS", "Tailwind CSS", "GitHub Pages"],
    description: " A lightweight Next.js portfolio deployed via GitHub Pages and TailwindCSS.",
  },
  {
    id: 170,
    author: "Sarah Dayan",
    screenshot: "/id170.png",
    liveUrl: "https://www.sarahdayan.dev/",
    githubUrl: "None",
    techStack: [	"NextJS", "Tailwind CSS", "NodeJS", "Vercel"],
    description: "A clean and efficient developer site built with Next.js and Vercel.",
  },
  {
    id: 171,
    author: "Theodorus Clarence",
    screenshot: "/id171.png",
    liveUrl: "https://theodorusclarence.com/",
    githubUrl: "https://github.com/theodorusclarence/theodorusclarence.com",
    techStack: ["NextJS", "TypeScript", "Tailwind CSS", "MDX Bundler", "Prisma"],
    description: "A feature-rich TypeScript portfolio using MDX and TailwindCSS.",
  },
  {
    id: 172,
    author: "Arafat Islam",
    screenshot: "/id172.png",
    liveUrl: "https://portfolio-khaki-iota-89.vercel.app/",
    githubUrl: "https://github.com/arafat4693/portfolio",
    techStack: ["NextJS", "TypeScript", "GraphQL", "Tailwind CSS"],
    description: "A developer portfolio using Next.js, GraphQL, and TailwindCSS.",
  },
  {
    id: 173,
    author: "Siddharth Verma",
    screenshot: "/id173.png",
    liveUrl: "https://iamdev.netlify.app/home.html",
    githubUrl: "None",
    techStack: [	"Tailwind", "Javascript", "React", "html/CSS"],
    description: " A simple yet functional React portfolio using Tailwind and vanilla JS.",
  },
  {
    id: 174,
    author: "Abo Ghanbari",
    screenshot: "/id174.png",
    liveUrl: "https://www.aboghanbari.com/",
    githubUrl: "None",
    techStack: [	"Gatsby", "Emotion", "GSAP", "Preact"],
    description: "A creative Gatsby portfolio powered by GSAP and Emotion.",
  },
  {
    id: 175,
    author: "PATRICK T.LO",
    screenshot: "/id175.png",
    liveUrl: "https://pleaseleaveon.com/",
    githubUrl: "None",
    techStack: [	"HTML5", "CSS", "JavaScript", "jQuery"],
    description: "A fun static HTML/CSS portfolio with subtle jQuery interactivity.",
  },
  {
    id: 176,
    author: "Aliyah Adefolake",
    screenshot: "/id176.png",
    liveUrl: "https://www.aliyahadefolake.com/",
    githubUrl: "None",
    techStack: [	"ReactJS", "Gatsby", "SASS", "GSAP", "Contentful"],
    description: "A visually dynamic personal site built with Gatsby and GSAP, showcasing creative portfolio and animations.",
  },
  {
    id: 177,
    author: "Travis Fischer",
    screenshot: "/id177.png",
    liveUrl: "https://transitivebullsh.it/",
    githubUrl: "https://github.com/transitive-bullshit/nextjs-notion-starter-kit",
    techStack: ["NextJS", "TypeScript", "Notion API", "Vercel"],
    description: "Minimalist and clean personal site built on Notion-powered Next.js starter kit.",
  },
  {
    id: 178,
    author: "Lynn Fisher",
    screenshot: "/id178.png",
    liveUrl: "https://lynnandtonic.com/",
    githubUrl: "https://github.com/lynnandtonic/lynnandtonic.com",
    techStack: ["HTML5", "CSS", "JavaScript", "SVG", "Netlify", "GoatCounter", "HSTS", "Open Graph"],
    description: " Creative, responsive site with artistic layouts and experimental CSS designs.",
  },
  {
    id: 179,
    author: "Danny Garcia",
    screenshot: "/id179.png",
    liveUrl: "https://danny-garcia.com/",
    githubUrl: "https://github.com/dannygarcia/dannygarcia.github.com",
    techStack: [	"HTML5", "CSS", "JavaScript", "TypeScript", "GLSL", "Netlify"],
    description: "Portfolio with stunning WebGL experiments and creative coding visuals.",
  },
  {
    id: 180,
    author: "Robin Payot",
    screenshot: "/id180.png",
    liveUrl: "http://www.robinpayot.com/",
    githubUrl: "None",
    techStack: ["HTML5", "CSS", "JavaScript", "GSAP", "Howler.js", "Hammer.js", "three.js", "WebGL", "PWA", "Open Graph", "Apache"],
    description: "Immersive, interactive web experience using WebGL, animations, and sound.",
  },
  {
    id: 181,
    author: "Jesse Zhou",
    screenshot: "/id181.png",
    liveUrl: "https://jesse-zhou.com/",
    githubUrl: "https://github.com/enderh3art/Ramen-Shop",
    techStack: ["HTML5", "CSS", "JavaScript", "GLSL", "Howler.js", "GSAP", "Three.js", "Node.js", "Vercel"],
    description: " A rich visual site featuring 3D animations, music, and shaders in a ramen shop theme.",
  },
  {
    id: 182,
    author: "Rauno Freiberg",
    screenshot: "/id182.png",
    liveUrl: "https://rauno.me/",
    githubUrl: "None",
    techStack: ["NextJS", "NodeJS", "Stiches", "Vercel"],
    description: "A modern, clean developer portfolio with a strong emphasis on UI and typography.",
  },
  {
    id: 183,
    author: "Anurag Hazra",
    screenshot: "/id183.png",
    liveUrl: "https://anuraghazra.dev/",
    githubUrl: "https://github.com/anuraghazra/anuraghazra.github.io",
    techStack: [	"React", "Gatsby", "Styled-components", "Cypress", "Jest", "TravisCI"],
    description: "Developer blog and portfolio with Gatsby and CI tools like Travis and Jest.",
  },
  {
    id: 184,
    author: "Hardik Gohil",
    screenshot: "/id184.jpg",
    liveUrl: "https://hardikgohilhlr.tech/",
    githubUrl: "None",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Firebase"],
    description: "Tech-focused portfolio highlighting Firebase-powered Next.js development.",
  },
  {
    id: 185,
    author: "Jonathan Toon",
    screenshot: "/id185.png",
    liveUrl: "https://jonathontoon.com/",
    githubUrl: "https://github.com/jonathontoon/jonathontoon.com",
    techStack: ["Gulp", "EsBuild", "postCSS", "Nunjuck"],
    description: " Developer site using static site generation with Gulp and Nunjuck templating.",
  },
  {
    id: 186,
    author: "Rafael Derolez",
    screenshot: "/id186.png",
    liveUrl: "https://derolez.dev/",
    githubUrl: "None",
    techStack: [	"NextJS", "Sanity", "ChakraUI", "Emotion"],
    description: " A slick personal portfolio with a minimal design using Sanity CMS and Chakra UI.",
  },
  {
    id: 187,
    author: "Chris Williams",
    screenshot: "/id187.png",
    liveUrl: "https://astro-theme-cactus.netlify.app/",
    githubUrl: "https://github.com/chrismwilliams/astro-theme-cactus",
    techStack: ["Astro", "Typescript", "Tailwind CSS", "MDX"],
    description: "A professional blog using Astro theme with Tailwind and MDX integration.",
  },
  {
    id: 188,
    author: "Ben Holmes",
    screenshot: "/id188.png",
    liveUrl: "https://bholmes.dev/",
    githubUrl: "https://github.com/bholmesdev/bholmesdev",
    techStack: [	"Gatsby", "Javascript", "SCSS", "Pug"],
    description: "Developer blog and portfolio powered by Gatsby and handcrafted components.",
  },
  {
    id: 189,
    author: "Yasio",
    screenshot: "/id189.png",
    liveUrl: "https://yasio.dev/",
    githubUrl: "https://github.com/YasiOnFire",
    techStack: ["Nuxt.js", "Node.js", "core-js", "Vue.js", "VideoJS", "Firebase", "HSTS", "Open Graph", "HTTP/3", "Webpack", "PWA"],
    description: " Multimedia-focused site with Vue.js and a broad set of advanced frontend tools.",
  },
  {
    id: 190,
    author: "Alec Babala",
    screenshot: "/id190.png",
    liveUrl: "https://www.alecbabala.com/",
    githubUrl: "None",
    techStack: [	"Next.js", "Node.js", "core-js", "React", "HSTS", "Open Graph", "Webpack", "MobX", "GSAP", "Contentful"],
    description: "A polished React-based portfolio with motion effects and CMS integration.",
  },
  {
    id: 191,
    author: "Gavin Nelson",
    screenshot: "/id191.png",
    liveUrl: "https://nelson.co/",
    githubUrl: "https://github.com/gavinmn/nelson.co",
    techStack: ["NextJS", "Tailwind CSS", "Vercel", "MDX"],
    description: "Clean and elegant portfolio powered by Next.js and styled with Tailwind.",
  },
  {
    id: 192,
    author: "Yinka Adedire",
    screenshot: "/id192.png",
    liveUrl: "https://www.yinka.codes/",
    githubUrl: "https://github.com/yinkakun/yinkakun-portfolio",
    techStack: [	"Gatsby", "ReactJS", "Styled-Components"],
    description: "A vibrant personal site built using Gatsby and styled-components.",
  },
  {
    id: 193,
    author: "Abdullah Abdulfatah",
    screenshot: "/id193.png",
    liveUrl: "https://www.draq.tech/",
    githubUrl: "None",
    techStack: ["NextJS", "Typescript", "ChakraUI"],
    description: "Developer portfolio using Chakra UI and Next.js with a clean layout.",
  },
  {
    id: 194,
    author: "Samuel Imolorhe",
    screenshot: "/id194.png",
    liveUrl: "https://www.xkoji.dev/",
    githubUrl: "https://github.com/imolorhe/xkoji-code",
    techStack: [	"Gatsby", "GSAP", "JavaScript", "Netlify"],
    description: "Portfolio with GSAP animations and fast Gatsby deployment on Netlify.",
  },
  {
    id: 195,
    author: "Abu Said",
    screenshot: "/id195.png",
    liveUrl: "https://abusaid.netlify.app/",
    githubUrl: "https://github.com/said7388/developer-portfolio",
    techStack: ["Next.js", "Tailwind CSS", "Email.JS"],
    description: "Simple, effective portfolio with Tailwind and integrated contact via Email.js.",
  },
  {
    id: 196,
    author: "Quiet Node",
    screenshot: "/id196.png",
    liveUrl: "https://quiet-node.dev/",
    githubUrl: "https://github.com/quiet-node/portfolio-v2",
    techStack: [	"TypeScript", "ReactJS", "ViteJS", "TailwindCSS", "Motion Framer"],
    description: " Motion-rich developer site built with React and Framer Motion.",
  },
  {
    id: 197,
    author: "Daniel Wisky",
    screenshot: "/id197.png",
    liveUrl: "https://danielwisky.com.br/",
    githubUrl: "https://github.com/danielwisky/danielwisky.github.io",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Basic personal website crafted with pure HTML, CSS, and JavaScript.",
  },
  {
    id: 198,
    author: "JJ Kasper",
    screenshot: "/id198.png",
    liveUrl: "https://jjsweb.site/",
    githubUrl: "https://github.com/ijjk/jjsweb.site",
    techStack: ["NextJS", "Vercel", "CSS"],
    description: " Lightweight and fast personal site using Next.js and hosted on Vercel.",
  },
  {
    id: 199,
    author: "Cassidy Williams",
    screenshot: "/id199.png",
    liveUrl: "https://cassidoo.co/",
    githubUrl: "None",
    techStack: ["HTML", "CSS"," JavaScript"],
    description: " Fun, expressive personal homepage with classic HTML/CSS charm.",
  },
  {
    id: 200,
    author: "Jahir Fiquitiva",
    screenshot: "/id200.png",
    liveUrl: "https://jahir.dev/",
    githubUrl: "https://github.com/jahirfiquitiva/jahir.dev",
    techStack: ["Next.js", "Tailwind CSS", "MDX", "contentlayer", "PlanetScale"," Vercel", "TypeScript"],
    description: "Feature-rich developer blog with Tailwind, MDX, and contentlayer on Vercel.",
  },
  {
    id: 311,
    author: "Nisarg Kavi",
    screenshot: "/id311.png",
    liveUrl: "https://www.nisargkavi.in/",
    githubUrl: "	None",
    techStack: ["Nextjs", "Tailwind CSS", "Framer Motion", "AnimeJS"],
    description: "Modern Next.js portfolio with smooth Framer Motion animations and AnimeJS for interactive elements, styled with Tailwind CSS.",
  },
  {
    id: 312,
    author: "Malik Naik",
    screenshot: "/id312.png",
    liveUrl: "https://www.maliknaik.me/",
    githubUrl: "None",
    techStack: [	"HTML", "CSS", "Bootstrap", "JavaScript"],
    description: "Clean and responsive portfolio built with vanilla web technologies and Bootstrap framework for mobile-first design.",
  },
  {
    id: 313,
    author: "Kshitij Gehlot",
    screenshot: "/id313.png",
    liveUrl: "https://kdgehlot2003.github.io/Portfolio/",
    githubUrl: "https://github.com/KDGehlot2003/Portfolio",
    techStack: ["HTML", "CSS"," Bootstrap",  "JavaScript"],
    description: "Simple yet effective GitHub Pages portfolio showcasing frontend skills with Bootstrap and vanilla JavaScript.",
  },
  {
    id:314 ,
    author: "Johnson Takashi",
    screenshot: "/id314.jpg",
    liveUrl: "https://johnson-takashi-blockchain.web.app/",
    githubUrl: "https://github.com/John-T45/John-T45.github.io",
    techStack: ["HTML", "CSS", "Bootstrap", "and JavaScript"],
    description: "Blockchain-focused portfolio with modern web technologies, featuring responsive design and interactive elements.",
  },
  {
    id: 315,
    author: "Shivaraj Kolekar",
    screenshot: "/id315.png",
    liveUrl: "https://shivaraj-portfolio.vercel.app/",
    githubUrl: "https://github.com/Shivaraj-Kolekar/portfolio",
    techStack: ["HTML", "TailwindCSS", "Javascript"],
    description: "Minimalist portfolio built with HTML, TailwindCSS for utility-first styling, and JavaScript for interactivity.",
  },
  {
    id: 316,
    author: "Shubham Gaur",
    screenshot: "/id316.png",
    liveUrl: "https://shubhamessier.github.io/portfolio",
    githubUrl: "https://github.com/shubhamessier/portfolio",
    techStack: ["HTML", "CSS " ,"JavaScript"],
    description: "GitHub Pages portfolio showcasing vanilla web development skills with clean HTML, CSS, and JavaScript implementation.",
  },
  {
    id: 317,
    author: "Atijosan Iyanuoluwa",
    screenshot: "/id317.png",
    liveUrl: "https://iyanu-codes-v1.vercel.app/",
    githubUrl: "https://github.com/Iyanu1396",
    techStack: [	"REACTJS", "TALWINDCSS "," Other Libraries"],
    description: "React-based portfolio with TailwindCSS styling and additional libraries for enhanced user experience and modern design.",
  },
  {
    id: 318,
    author: "Mahmoud Ibrahim",
    screenshot: "/id318.png",
    liveUrl: "https://mahmoudibrahim.me/",
    githubUrl: "None",
    techStack: [	"React", "Strapi", "Bootstrap", "TypeScript", "Netlify"],
    description: "Full-stack portfolio with React frontend and Strapi headless CMS, featuring TypeScript and Bootstrap for robust development.",
  },
  {
    id: 319,
    author: "Archit Agrawal",
    screenshot: "/id319.jpg",
    liveUrl: "https://archit-agrawal-portfolio.vercel.app/",
    githubUrl: "https://github.com/ArchitAgrawal25/Portfolio",
    techStack: ["HTML", "CSS", " JavaScript"],
    description: "Clean and professional portfolio demonstrating core web technologies with responsive design and smooth interactions.",
  },
  {
    id: 320,
    author: "Vaishnavi Shelke",
    screenshot: "/id320.png",
    liveUrl: "https://vsp-portfolio.netlify.app/",
    githubUrl: "https://github.com/vaishnavishelke2021/Portfolio-Website",
    techStack: [	"HTML", "CSS", "Bootstrap", "Netlify"],
    description: "Netlify-deployed portfolio showcasing frontend development skills with Bootstrap framework and responsive design.",
  },
  {
    id: 321,
    author: "Timothy Klint",
    screenshot: "/id321.jpg",
    liveUrl: "https://tjklint.github.io/",
    githubUrl:"https://github.com/tjklint/tjklint.github.io",
    techStack: ["React", "TypeScript", "SASS"],
    description: "GitHub Pages portfolio built with React, TypeScript for type safety, and SASS for advanced CSS preprocessing.",
  },
  {
    id: 322,
    author: "Pravin Mane",
    screenshot: "/id322.jpg",
    liveUrl: "https://www.pravinmane.com/",
    githubUrl: "https://github.com/pravinmane1/Portfolio",
    techStack: ["Angular", "HTML", "SCSS", "TypeScript", "gh-pages"],
    description: "Angular-based portfolio with TypeScript, SCSS styling, and GitHub Pages deployment for showcasing development expertise.",
  },
  {
    id: 323,
    author: "yuxxeun",
    screenshot: "/id323.png",
    liveUrl: "https://yuxxeun.xyz/",
    githubUrl: "https://github.com/yuxxeun",
    techStack: ["Next.js", "Tailwind", "Supabase", "Vercel"],
    description: "Modern Next.js portfolio with Supabase backend integration, styled with Tailwind CSS and deployed on Vercel for optimal performance.",
  },
  {
    id: 324,
    author: "Shivam Javiya",
    screenshot: "/id324.jpg",
    liveUrl: "https://shivamjaviya.netlify.app/",
    githubUrl: "https://github.com/ShivamJaviya/Shivam_Portfolio",
    techStack: ["HTML", "CSS", "JS"],
    description: "Netlify-hosted portfolio demonstrating fundamental web development skills with clean HTML, CSS, and JavaScript implementation.",
  },
  {
    id: 325,
    author: "Krishnakumar Valliappan",
    screenshot: "/id325.jpg",
    liveUrl: "https://www.krishnakumar.dev/",
    githubUrl: "https://github.com/krishnavalliappan/portfolio-website",
    techStack: ["Next.js", "Framer", "TypeScript", "TailwindCSS", "shadcn/ui"],
    description: "Advanced Next.js portfolio with Framer Motion animations, TypeScript, TailwindCSS, and shadcn/ui components for modern design.",
  },
  {
    id: 326,
    author: "Gokul Raja",
    screenshot: "/id326.png",
    liveUrl: "https://gokul-raja84.github.io/",
    githubUrl: "https://github.com/Gokul-Raja84/gokul-raja84.github.io",
    techStack: ["React", "styled-components", "GraphQL", "UnDraw", "Github Pages"],
    description: "A modern React portfolio featuring styled-components for component styling, GraphQL for data management, and UnDraw illustrations for visual appeal, deployed on GitHub Pages.",
  },
  {
    id: 327,
    author: "Abdelrahman Ahmed",
    screenshot: "/id327.jpg",
    liveUrl: "https://abdalrahman.tech/",
    githubUrl: "https://github.com/AB-DALRAHM-AN",
    techStack: ["Next.js", "TypeScript", "TailwindCss", "Shadcn/ui", "Notion", "Vercel", "Resend", "ReactEmail"],
    description: "Comprehensive Next.js portfolio with Notion integration, TypeScript, TailwindCSS, shadcn/ui components, and email functionality via Resend and ReactEmail.",
  },
  {
    id: 328,
    author: "Jiseeeh",
    screenshot: "/id328.jpg",
    liveUrl: "https://jiseeeh.codes/",
    githubUrl: "https://github.com/Jiseeeh/portfolio-revamp",
    techStack: ["Next.js", "TailwindCSS", "GSAP", "Vercel", "PostHog"],
    description: "Developer portfolio with Next.js, GSAP animations, TailwindCSS styling, PostHog analytics, and Vercel deployment for performance.",
  },
  {
    id: 329,
    author: "Ghulam Ahmed",
    screenshot: "/id329.jpg",
    liveUrl: "https://gahmed.com/",
    githubUrl: "https://github.com/theghulam",
    techStack: ["Astro", "Solid.js", "TypeScript", "TailwindCSS"],
    description: "Modern Astro-based portfolio with Solid.js components, TypeScript for type safety, and TailwindCSS for responsive styling.",
  },
  {
    id: 330,
    author: "Carson Spriggs",
    screenshot: "/id330.png",
    liveUrl: "https://carsonsgit.github.io/",
    githubUrl: "https://github.com/carsonSgit/carsonsgit.github.io",
    techStack: ["React", "TypeScript", "SCSS"],
    description: "GitHub Pages portfolio showcasing React development skills with TypeScript and SCSS for advanced styling capabilities.",
  },
  {
    id: 331,
    author: "Nicholas Gannon",
    screenshot: "/id331.png",
    liveUrl: "https://nicholasgannon.io/",
    githubUrl: "https://github.com/NicholasGannon/Portfolio",
    techStack: ["HTML", "TailwindCSS", "JavaScript"],
    description: "Clean and responsive portfolio built with HTML, TailwindCSS, and JavaScript for modern web development.",
  },
  {
    id: 332,
    author: "Chung Nguyen Thanh",
    screenshot: "/id332.png",
    liveUrl: "https://chunhthanhde.github.io/",
    githubUrl: "https://github.com/chunhthanhde",
    techStack: ["Flutter", "Dart", "Github Pages"],
    description: "Flutter-based portfolio with Dart programming language, deployed on GitHub Pages for cross-platform mobile development showcase.",
  },
  {
    id: 333,
    author: "Babatunde Afreka",
    screenshot: "/id333.png",
    liveUrl: "https://bafrekauiux.framer.website/",
    githubUrl: "None",
    techStack: ["Framer", "React"],
    description: "Modern React portfolio built with Framer for interactive animations and smooth user experience design.",
  },
  {
    id: 334,
    author: "LNLenost",
    screenshot: "/id334.png",
    liveUrl: "https://lnlenost.netlify.app/",
    githubUrl: "https://github.com/LNLenost/lnlenost.github.io",
    techStack: ["HTML", "SASS", "JavaScript"],
    description: "Netlify-hosted portfolio showcasing HTML, SASS preprocessing, and JavaScript for clean and modern web development.",
  },
  {
    id: 335,
    author: "Shivam Panchal",
    screenshot: "/id335.jpg",
    liveUrl: "https://shivampanchal.vercel.app/",
    githubUrl: "None",
    techStack: ["ReactJS", "CSS"],
    description: "Vercel-deployed React portfolio with CSS styling for clean component-based design and responsive layout.",
  },
  {
    id: 336,
    author: "Mariya Baig",
    screenshot: "/id336.png",
    liveUrl: "https://mariyabaig.vercel.app/",
    githubUrl: "None",
    techStack: ["NextJS", "TailwindCSS"],
    description: "Next.js portfolio with TailwindCSS for utility-first styling and modern web development practices.",
  },
  {
    id: 337,
    author: "Ketuman",
    screenshot: "/id337.jpg",
    liveUrl: "https://k2maan.vercel.app/",
    githubUrl: "None",
    techStack: ["NextJS", "TailwindCSS"],
    description: "Vercel-hosted Next.js portfolio with TailwindCSS for responsive design and modern development workflow.",
  },
  {
    id: 338,
    author: "Adeola Badero",
    screenshot: "/id338.jpg",
    liveUrl: "https://adeolabadero.vercel.app/",
    githubUrl: "https://github.com/adex-hub/ade-folio",
    techStack: ["Nextjs", "Tailwind CSS", "TypeScript", "Framer Motion", "Vercel"],
    description: "Advanced Next.js portfolio with TypeScript, Framer Motion animations, Tailwind CSS, and Vercel deployment for optimal performance.",
  },
  {
    id: 339,
    author: "Tanuj Chakraborty",
    screenshot: "/id339.jpg",
    liveUrl: "https://github.com/vchaitanyachowdari/portfolio-ideas-1/blob/main/iamtj.dev",
    githubUrl: "https://github.com/i-am-tj/iamtj.dev",
    techStack: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    description: "Full-stack React portfolio with Next.js, TypeScript, and Tailwind CSS for modern web development practices.",
  },
  {
    id: 340,
    author: "Akshay",
    screenshot: "/id340.jpg",
    liveUrl: "https://devakshay.vercel.app/",
    githubUrl: "https://github.com/Akshayp2002",
    techStack: ["Angular", "TypeScript", "HTML", "Tailwind CSS", "Vercel", "Flowbite"],
    description: "Angular portfolio with TypeScript, Tailwind CSS, and Flowbite components for modern web development and responsive design.",
  },
  {
    id: 341,
    author: "Hari Thatikonda",
    screenshot: "/id341.jpg",
    liveUrl: "https://thughari.github.io/",
    githubUrl: "https://github.com/thughari/thughari.github.io",
    techStack: ["HTML", "CSS", "JS", "Google sheets integrated responses with mail notification(app script)"],
    description: "Interactive portfolio with HTML, CSS, JavaScript, and Google Sheets integration for dynamic contact forms and mail notifications.",
  },
  {
    id: 342,
    author: "Sawad",
    screenshot: "/342.jpeg",
    liveUrl: "https://sawad.framer.website/",
    githubUrl: "None",
    techStack: ["Framer"],
    description: "Framer-based portfolio showcasing modern design principles and interactive user experience with smooth animations.",
  },
  {
    id: 343,
    author: "Carlos Dubón",
    screenshot: "/343.jpg",
    liveUrl: "https://carlosdubon.dev/",
    githubUrl: "None",
    techStack: ["Next.js 14 (App Router)", "TailwindCSS", "TypeScript", "Framer Motion", "Velite"],
    description: "Next.js 14 portfolio with App Router, TypeScript, TailwindCSS, Framer Motion animations, and Velite for modern web development.",
  },
  {
    id: 344,
    author: "Umesh Nagare",
    screenshot: "/344.jpg",
    liveUrl: "https://umeshnagare.com/",
    githubUrl: "https://github.com/Algoture/PortFolio",
    techStack: ["Next.js", "Tailwind", "Framer Motion"],
    description: "Next.js portfolio with Tailwind CSS and Framer Motion for smooth animations and modern responsive design.",
  },
  {
    id: 345,
    author: "Muhammad Essa",
    screenshot: "/345.png",
    liveUrl: "https://muhammadessa.vercel.app/",
    githubUrl: "https://github.com/imuhammadessa",
    techStack: ["React.js", "Next.js", "Tailwind", "MUI", "Vercel"],
    description: "Full-stack React portfolio with Next.js, MUI components, Tailwind CSS, and Vercel deployment for modern web applications.",
  },
  {
    id: 346,
    author: "Farouk Mustapha",
    screenshot: "/346.jpg",
    liveUrl: "https://devfarouk.vercel.app/",
    githubUrl: "https://github.com/Farouk-ayo/devfarouk",
    techStack: ["NextJs", "Typescript", "TailwindCSS", "AOS"],
    description: "Next.js portfolio with TypeScript, TailwindCSS, and AOS animations for smooth scrolling and modern user experience.",
  },
  {
    id: 347,
    author: "Sachin Desai",
    screenshot: "/347.jpg",
    liveUrl: "https://sachindesai.in/",
    githubUrl: "https://github.com/sachind3/finalportfolio",
    techStack: ["Next Js 14", "Tailwind CSS", "Vercel", "GSAP", "CSS", "Locomotive Scroll"],
    description: "Next.js 14 portfolio with TailwindCSS, GSAP animations, Locomotive Scroll, and Vercel deployment for cutting-edge web experience.",
  },
  {
    id: 348,
    author: "Rauliqbal",
    screenshot: "/348.png",
    liveUrl: "https://rauliqbal.vercel.app/",
    githubUrl: "	None",
    techStack: ["Next JS", "TypeScript", "Tailwind CSS", "Framer Motion", "Supabase"],
    description: "Next.js portfolio with TypeScript, TailwindCSS, Framer Motion animations, and Supabase backend for modern full-stack development.",
  },
  {
    id: 349,
    author: "TSolutionsX",
    screenshot: "/349.jpg",
    liveUrl: "https://techsolutionsx.vercel.app/",
    githubUrl: "None",
    techStack: ["NextJS", "TailwindCSS"],
    description: "Vercel-deployed Next.js portfolio with TailwindCSS for clean, modern web development and responsive design.",
  },
  {
    id: 350,
    author: "Chun-Ho (Hugo) Lin",
    screenshot: "/350.jpg",
    liveUrl: "https://1chooo.com/",
    githubUrl: "https://github.com/1chooo/1chooo.com",
    techStack: ["ReactJS", "Next.js", "Nextra (V3)", "TypeScript"],
    description: "Next.js portfolio with Nextra v3, ReactJS, TypeScript, and modern documentation-focused design for technical content.",
  },
  {
    id: 351,
    author: "Priyanshu Tiwari",
    screenshot: "/351.jpg",
    liveUrl: "https://priyanshu-tiwari.vercel.app/",
    githubUrl: "https://github.com/priyanshtiwari001/portfolio",
    techStack: ["NextJS", "TailwindCSS", "TypeScript", "ThreeJS"],
    description: "Next.js portfolio with TypeScript, TailwindCSS, and Three.js for immersive 3D graphics and modern web development.",
  },
  {
    id: 352,
    author: "Durgesh",
    screenshot: "/352.jpg",
    liveUrl: "https://yodkwtf.com/",
    githubUrl: "https://github.com/yodkwtf/yodkwtf.com",
    techStack: ["ReactJS", "CSS", "Context API", "Airtable CMS"],
    description: "Creative React portfolio with Airtable CMS integration and Context API for state management, featuring modern design and smooth animations.",
  },
  {
    id: 353,
    author: "Mihir",
    screenshot: "/353.jpg",
    liveUrl: "https://mihir-portfolio-main-777.vercel.app/",
    githubUrl: "https://github.com/MIHIR2006/mihir-portfolio",
    techStack: ["React", "Framer", "GSAP", "EmailJS"],
    description: "Dynamic React portfolio showcasing advanced animations with Framer Motion and GSAP, featuring interactive elements and EmailJS integration.",
  },
  {
    id: 354,
    author: "Aditya Bansal",
    screenshot: "/354.jpg",
    liveUrl: "https://www.adityabansal.tech/",
    githubUrl: "None",
    techStack: ["Three js", "R3F", "React Js", "Framer Motion", "GSAP"],
    description: "Immersive 3D portfolio built with Three.js and React Three Fiber, featuring stunning visual effects and smooth animations.",
  },
  {
    id: 355,
    author: "Nafis Mahmud Ayon",
    screenshot: "/355.png",
    liveUrl: "https://nafisbd.com/",
    githubUrl: "https://github.com/NafisMahmudAyon/Portfolio-NafisBd.com-v2",
    techStack: ["React Js", "Framer Motion", "NextJS", "TailwindCSS", "TypeScript"],
    description: "Modern Next.js portfolio with TypeScript, featuring elegant animations with Framer Motion and responsive TailwindCSS styling.",
  },
  {
    id: 356,
    author: "Ata Berkay Karakuş",
    screenshot: "/356.png",
    liveUrl: "https://berkaykrks.netlify.app/",
    githubUrl: "https://github.com/berkaykrks/personal-website",
    techStack: ["HTML", "CSS", "JS"],
    description: "Clean vanilla web portfolio showcasing fundamental web technologies with modern design principles and smooth interactions.",
  },
  {
    id: 357,
    author: "Salim Rutaganda",
    screenshot: "/357.png",
    liveUrl: "https://www.rsalim.vercel.app/",
    githubUrl: "https://github.com/rutaganda-salim/devfolio",
    techStack: ["React", "Next.js", "Tailwindcss", "TypeScript"],
    description: "Professional developer portfolio built with Next.js and TypeScript, featuring responsive design and modern development practices.",
  },
  {
    id: 358,
    author: "Culture DevOps",
    screenshot: "/358.png",
    liveUrl: "https://culturedevops.com/en",
    githubUrl: "https://github.com/CultureDevOps/blog",
    techStack: ["Next.js", "Tailwind CSS", "i18n"],
    description: "Internationalized Next.js blog portfolio with multi-language support, built with Tailwind CSS for modern styling and accessibility.",
  },
  {
    id: 359,
    author: "Hanif Yuli Abdillah P",
    screenshot: "/359.png",
    liveUrl: "https://hanifabdlh.vercel.app/",
    githubUrl: "	None",
    techStack: ["Python", "HTML", "CSS", "JS"],
    description: "Full-stack portfolio showcasing Python backend capabilities with modern frontend technologies and responsive design.",
  },
  {
    id: 360,
    author: "Manish Tamang",
    screenshot: "/360.png",
    liveUrl: "https://manishtamang.com/",
    githubUrl: "None",
    techStack: ["Next.js", "TailwindCSS", "React", "Sanity"],
    description: "Next.js portfolio integrated with Sanity CMS for dynamic content management, featuring modern React components and TailwindCSS styling.",
  },
  {
    id: 361,
    author: "Aditya Punmiya",
    screenshot: "/361.png",
    liveUrl: "https://adityapunmiya.com/",
    githubUrl: "https://github.com/Aditya-0011/portfolio-website",
    techStack: ["Next.js", "Tailwind CSS", "TypeScript", "MongoDB", "Nodemailer", "Zod"],
    description: "Full-stack Next.js portfolio with MongoDB integration, TypeScript, and email functionality, featuring robust validation with Zod.",
  },
  {
    id: 362,
    author: "Divyansh Kathuria",
    screenshot: "/362.png",
    liveUrl: "https://divyanshkathuria.netlify.app/",
    githubUrl: "https://github.com/DIVYANSHKATHURIA",
    techStack: ["HTML", "CSS", "React", "Three.js"],
    description: "Interactive portfolio featuring Three.js 3D graphics with React integration, showcasing creative web development and immersive user experiences.",
  },
  {
    id: 363,
    author: "Aditya Induraj",
    screenshot: "/363.png",
    liveUrl: "https://adityainduraj.xyz/",
    githubUrl: "https://adityainduraj.xyz/",
    techStack: ["Nextjs", "Tailwind CSS", "TypeScript", "Vercel"],
    description: "Modern Next.js portfolio with TypeScript, Tailwind CSS, and Vercel deployment for optimal performance and developer experience.",
  },
  {
    id: 364,
    author: "Srijan Baniyal",
    screenshot: "/364.png",
    liveUrl: "https://srijanbaniyal.com/",
    githubUrl: "None",
    techStack: ["Next.js", "Tailwindcss", "Typescript", "Shadcn-UI", "Framer Motion"],
    description: "Advanced Next.js portfolio with Shadcn-UI components, TypeScript, Tailwind CSS, and Framer Motion for smooth animations and modern design.",
  },
  {
    id: 365,
    author: "Mathis Zeghouani",
    screenshot: "/365.png",
    liveUrl: "https://mathisdev.pro/",
    githubUrl: "https://github.com/mathisdev7/my-portfolio",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Vercel"],
    description: "Professional developer portfolio showcasing Next.js, React, TypeScript, and Tailwind CSS with Vercel deployment for optimal performance.",
  },
  {
    id: 366,
    author: "Deepak Modi",
    screenshot: "/366.png",
    liveUrl: "https://deepakmodi.tech/",
    githubUrl: "https://github.com/decodewithdeepak/Portfolio",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Vercel"],
    description: "Clean and modern Next.js portfolio with React components, TypeScript for type safety, and Tailwind CSS styling deployed on Vercel.",
  },
  {
    id: 367,
    author: "Madhurima Rawat",
    screenshot: "/367.png",
    liveUrl: "https://madhurimarawat.github.io/Portfolio-Website/",
    githubUrl: "https://github.com/madhurimarawat/Portfolio-Website",
    techStack: ["HTML", "CSS", "JS", "Bootstrap"],
    description: "GitHub Pages portfolio built with HTML, CSS, JavaScript, and Bootstrap for responsive design and clean web development practices.",
  },
  {
    id: 368,
    author: "Abass Dev",
    screenshot: "/368.png",
    liveUrl: "https://abassdev.com/",
    githubUrl: "https://github.com/abass-dev/abassdev.com",
    techStack: ["NextJs", "Tailwind CSS", "TypeScript"],
    description: "Next.js portfolio with TypeScript and Tailwind CSS for modern web development, featuring clean design and responsive layout.",
  },
  {
    id: 369,
    author: "Kavan Bhavsar",
    screenshot: "/369.png",
    liveUrl: "https://kavan-bhavsar.vercel.app/",
    githubUrl: "None",
    techStack: ["Next.js", "Tailwind", "Framer Motion", "Convex", "Spline", "TypeScript", "Vercel"],
    description: "Advanced Next.js portfolio with Framer Motion animations, Convex backend, Spline 3D elements, and TypeScript for cutting-edge web experiences.",
  },
  {
    id: 370,
    author: "Vignesh Patali",
    screenshot: "/370.png",
    liveUrl: "https://vigh.me/",
    githubUrl: "None",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Threejs", "Vercel"],
    description: "Immersive Next.js portfolio featuring Three.js 3D graphics, React components, TypeScript, and Tailwind CSS for modern web development.",
  },
  {
    id: 371,
    author: "Rushikesh Nimkar",
    screenshot: "/371.png",
    liveUrl: "https://rushikeshnimkar.xyz/",
    githubUrl: "https://github.com/Rushikeshnimkar/portfolio2025.git",
    techStack: ["Next.js", "React", "Tailwind CSS", "TypeScript", "LangChain", "LangGraph", "openrouter"],
    description: "AI-powered Next.js portfolio with LangChain integration, React components, TypeScript, and modern AI/ML capabilities for innovative web experiences.",
  },
  {
    id: 372,
    author: "Tajmirul Islam",
    screenshot: "/372.png",
    liveUrl: "https://www.me.toinfinite.dev/",
    githubUrl: "None",
    techStack: ["Next.js", "GSAP", "Tailwind CSS", "TypeScript"],
    description: "Next.js portfolio with GSAP animations, TypeScript, and Tailwind CSS for smooth interactions and modern web development practices.",
  },
  {
    id: 373,
    author: "Aakash Rajbasnhi",
    screenshot: "/373.png",
    liveUrl: "https://aakashrajbanshi.com.np/",
    githubUrl: "None",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Clean vanilla web portfolio built with HTML, CSS, and JavaScript showcasing fundamental web development skills and responsive design.",
  },
  {
    id: 374,
    author: "Abdelkarim Ain",
    screenshot: "/374.png",
    liveUrl: "https://www.abdelkarimain.me/",
    githubUrl: "None",
    techStack: ["Next.js", "Sanity.io", "TypeScript", "Tailwindcss", "Shadcn ui"],
    description: "Modern Next.js portfolio with Sanity.io headless CMS, TypeScript, Tailwind CSS, and Shadcn UI components for dynamic content management.",
  },
  {
    id: 375,
    author: "Jawher Kallel",
    screenshot: "/375.png",
    liveUrl: "https://jawherkl-github-io.vercel.app/",
    githubUrl: "https://github.com/JawherKl",
    techStack: ["PHP", "JavaScript", "Go", "Java", "TypeScript"],
    description: "Multi-language portfolio showcasing PHP, JavaScript, Go, Java, and TypeScript expertise with modern web development practices.",
  },
  {
    id: 376,
    author: "Enes Hacısağır",
    screenshot: "/376.png",
    liveUrl: "https://www.enesehs.me/",
    githubUrl: "https://github.com/enesehs",
    techStack: ["Html", "CSS", "JavaScript", "GSAP"],
    description: "Creative portfolio with GSAP animations, vanilla HTML, CSS, and JavaScript for smooth interactions and modern web experiences.",
  },
  {
    id: 377,
    author: "Binil B",
    screenshot: "/377.png",
    liveUrl: "https://thegr8binil.me/",
    githubUrl: "https://github.com/thegr8binil/",
    techStack: ["Nextjs", "Motion", "Tailwind CSS", "TypeScript", "GSAP", "Vercel"],
    description: "Advanced Next.js portfolio with Motion and GSAP animations, TypeScript, Tailwind CSS, and Vercel deployment for cutting-edge web design.",
  },
  {
    id: 378,
    author: "Roman Mendaliev",
    screenshot: "/378.png",
    liveUrl: "https://roman.asd.lol/",
    githubUrl: "https://github.com/reacheight/home",
    techStack: ["HTML", "CSS", "JavaScript"],
    description: "Minimalist portfolio built with pure HTML, CSS, and JavaScript showcasing clean design principles and responsive web development.",
  },
  {
    id: 379,
    author: "Aditya Gupta",
    screenshot: "/379.png",
    liveUrl: "https://minimalist-portfolio-phi.vercel.app/",
    githubUrl: "https://github.com/impulseadi/minimalist_portfolio",
    techStack: ["React.js", "Tailwind CSS", "Framer Motion"],
    description: "Minimalist React portfolio with Tailwind CSS and Framer Motion for clean design and smooth animations on Vercel deployment.",
  },
  {
    id: 380,
    author: "Nat Anselm",
    screenshot: "/380.png",
    liveUrl: "https://nanselm.com/",
    githubUrl: "None",
    techStack: ["Astro", "DaisyUI", "TailwindCSS"],
    description: "Modern Astro-based portfolio with DaisyUI components and Tailwind CSS for fast, lightweight static site generation.",
  },
  {
    id: 381,
    author: "Uday G",
    screenshot: "/381.png",
    liveUrl: "https://portfoliov3-puce.vercel.app/",
    githubUrl: "https://github.com/oxBinaryBrain/Portfoilo_v3",
    techStack: ["TypeScript", "CSS", "Vercel", "Vite", "Nextjs"],
    description: "Next.js portfolio with TypeScript, Vite build tool, and CSS styling deployed on Vercel for optimal performance and modern development workflow.",
  },
  {
    id: 382,
    author: "Utkarsh Singhal",
    screenshot: "/382.png",
    liveUrl: "https://utkarsh-singhal.is-a.dev/",
    githubUrl: "https://github.com/Utkarsh-Singhal-26/portfolio",
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "ShadCN UI", "Vercel"],
    description: "Modern Next.js portfolio with ShadCN UI components, TypeScript, Tailwind CSS, and Vercel deployment for professional web development.",
  }
];

